#!/usr/bin/env bash

set -euo pipefail

pushd apps/deploy
yarn deploy
popd

aws ssm get-parameter --name /test/next-static-site-bucket --with-decryption --query Parameter.Value
# aws s3 sync apps/web/out s3://blashblah --delete