name: pipeline
on:
  push:
    branches:
      - master
jobs:
  dev:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          docker-compose -f ci/docker-compose.yml build build
          docker-compose -f ci/docker-compose.yml run build
          docker-compose -f ci/docker-compose.yml down
